### ISSUE TITLE
Android Multi thread Error

### ISSUE THREAD

**Issue by JinhyukLc** [netpyoung/SqlCipher4Unity3D#21] opened 2019-07-01 08:46 UTC
I ran quite heavy tasks on another thread like this.
```
void SomeMethod()
{
    m_Thread = new System.Threading.Thread(Run);
    m_Thread.Start();
}

void Run()
{
    // Heavy Tasks like CreateTable, InsertTable
}
```
This code works well in editor, iOS builds and latest android builds, but in below environments, everything stops or sometimes crashes without any throwing exceptions or debug messages,

- Unity 2018.4.0
- Below Android 6.0, (Maybe 6.1 or 7.0, Not occured on Android 8.0 or above)
- il2cpp

When I changed my code with single-threaded version, no bugs occured.

Also everything worked well before I updated this plugin. (My project used this since 2017 and I never updated until now).

Thanks.

**Comment by netpyoung** [comment] 2019-07-01 13:45
That's interesting.

- Currently [Sqlite3Connection.cs](https://github.com/netpyoung/SqlCipher4Unity3D/blob/8da606ec8400a211b9242cb0c6314c8a32fbdbed/SqlCipher4Unity3D/Assets/SqlCipher4Unity3D/Sqlite3Connection.cs#L739) using [Interlocked class](https://docs.microsoft.com/en-us/dotnet/api/system.threading.interlocked?view=netframework-4.6) for solving multithread issues.
    - I didn't check the output code of IL2CPP, but I doubt of that.
- For solving #1  , this repo using v3.5.9 which is latest version among sqlcipher v3s.
    - and you can check/download other versions from https://mvnrepository.com/artifact/net.zetetic/android-database-sqlcipher with [mvn command](https://github.com/netpyoung/SqlCipher4Unity3D/blob/master/Rakefile#L217)

**Comment by JinhyukLc** [comment] 2019-07-02 03:28
Thanks for fast reply!

I tried with some other versions(3.4, 3.3, 3.5.7) of android-data-sqlcipher and not worked. 😢

**Comment by netpyoung** [comment] 2019-07-02 03:52
- Which android platform are you using? 32bit or 64bit?
- Have you been tried `lock` before insert the table?
``` csharp
lock (o) {
 insert something..
}
```

Maybe It caused by IL2CPP..... or v3's problem...

**Comment by JinhyukLc** [comment] 2019-07-02 04:58
I set target architectures to both ARMv7 and ARM64. I tried both on Android 9.0 (Galaxy S9+) by `adb install --abi arm64-v8a xxxx.apk` and `adb install --abi armeabi-v7a xxxx.apk` and everything worked, But not on an Android 6.0 device(Galaxy note 4, which supports only ARMv7)..

I also note that I made only one more thread other than unity's main thread and every db operations run on that thread one by one.

**Comment by netpyoung** [comment] 2020-09-23 19:57
This issue is outdated. and I'm not sure Is this issue still exists on current Sqlcipher version. So I close this issue at this moment.

**Closed by netpyoung** 2020-09-23 19:57 UTC
